AWSTemplateFormatVersion: 2010-09-09
Description: >-
  subreg

Transform:
- AWS::Serverless-2016-10-31

Resources:

  DocumentsStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: split-tests/template.yaml
