version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "subreg-tutorial"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ff9eio9h3ku8"
s3_prefix = "subreg-tutorial"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
