AWSTemplateFormatVersion: 2010-09-09
Description: >-
  subreg

Transform:
  - AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: nodejs18.x
    Architectures:
      - x86_64
    MemorySize: 128
    Timeout: 10

Resources:
  CreateSplitTest:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-CreateSplitTest"
      Description: Creates a new split test
      CodeUri: ./
      Handler: create.handler
      Policies:
        # Give Create/Read/Update/Delete Permissions to the SampleTable
        - DynamoDBCrudPolicy:
            TableName: !Ref SplitTestsTable
      Environment:
        Variables:
          SPLIT_TESTS_TABLE: !Ref SplitTestsTable
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /
            Method: POST
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Sourcemap: true
        EntryPoints:
          - src/handlers/create.ts

  SplitAndRedirect:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-SplitAndRedirect"
      Description: Run the split test and redirect the client
      CodeUri: ./
      Handler: split.handler
      Policies:
        # Give Create/Read/Update/Delete Permissions to the SampleTable
        - DynamoDBReadPolicy:
            TableName: !Ref SplitTestsTable
      Environment:
        Variables:
          SPLIT_TESTS_TABLE: !Ref SplitTestsTable
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /{id}
            Method: GET
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Sourcemap: true
        EntryPoints:
          - src/handlers/split.ts

  SplitTestsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${AWS::StackName}-SplitTests"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH

Outputs:
  WebURL:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/"
